version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
  - source: /database.sql
    destination: /tmp/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
    - location: scripts/load_db.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
